parameters:
    jihel.plugin.mail_xpertise.proxy.api.class: Jihel\Plugin\MailXpertiseBundle\Proxy\ApiProxy

services:
    jihel.plugin.mail_xpertise.proxy.api:
        class: %jihel.plugin.mail_xpertise.proxy.api.class%
        arguments:
            - %jihel.plugin.mail_xpertise.apiKey%
            - %jihel.plugin.mail_xpertise.token%
            - %jihel.plugin.mail_xpertise.timeout%
            - %jihel.plugin.mail_xpertise.baseUrl%
            - %jihel.plugin.mail_xpertise.referer%
